routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', 'ParentLoginController@showLoginForm')->name('parent.showLoginForm');


Route::post('/ortu_login', 'ParentLoginController@login')->name('parent.login');
Route::post('/parent/logout', 'ParentLoginController@logout')->name('parent.logout');

Route::middleware('auth.parent:parent')->group(function(){
    Route::get('/parent/dashboard', 'DashboardController@index');
    Route::get('balita-anda', 'BalitaController@parentBabies');
    Route::get('pertumbuhan-balita-anda', 'PertumbuhanController@index')->name('pertumbuhan-balita-anda');
    Route::get('imunisasi-balita-anda', 'ImunisasiController@index')->name('imunisasi-balita-anda');
    Route::get('vitamin-balita-anda', 'VitaminController@index')->name('vitamin-balita-anda');
    Route::get('ubah-password', 'UbahPasswordController@index')->name('ubah-password');
    Route::post('ubah-password', 'UbahPasswordController@update')->name('ubah-password.update');
});
 
Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    
    Route::resource('jenis_imunisasi', 'JenisImunisasiController');    
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('balita', 'BalitaController');
    Route::resource('user', 'UserController');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');    

    Route::resource('pertumbuhan', 'PertumbuhanController');
    Route::resource('imunisasi', 'ImunisasiController');
    Route::resource('vitamin', 'VitaminController');

    Route::get('laporan', 'LaporanController@index')->name('laporan.index');

    Route::get('print-kunjungan/{jenis}/{tahun}', 'LaporanController@print')->name('print-kunjungan');
});

app/JenisImunisasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JenisImunisasi extends Model
{
    protected $table = "jenis_imunisasi";
    protected $fillable = ['nama_imunisasi', 'keterangan'];

    public function imunisasi()
    {
        return $this->hasMany('App\Imunisasi');
    }

    public function getDefaultValues()
    {
        return [
            'nama_imunisasi' => '',
            'keterangan' => ''
        ];
    }
}

app/Http/Controllers/JenisImunisasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\JenisImunisasi;

class JenisImunisasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('jenis_imunisasi/index', ['jenis_imunisasi' => JenisImunisasi::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $jm = new JenisImunisasi();
    
        $data['jenis_imunisasi'] = (object) $jm->getDefaultValues();
     
        return view('jenis_imunisasi/form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_imunisasi' => 'required',         
        ]);

        JenisImunisasi::create($request->all());
        return redirect()->route('jenis_imunisasi.index')->with('success', 'Berhasil menambah data jenis imunisasi');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['jenis_imunisasi'] = JenisImunisasi::find($id);
        return view('jenis_imunisasi.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_imunisasi' => 'required',         
        ]);

        JenisImunisasi::find($id)->update($request->all());
        return redirect()->route('jenis_imunisasi.index')->with('success', 'Berhasil mengubah data jenis imunisasi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        JenisImunisasi::find($id)->delete();
        return redirect()->route('jenis_imunisasi.index')->with('success', 'Berhasil menghapus data jenis imunisasi');
    }
}

resources/views/jenis_imunisasi/form.blade.php
@extends('layouts.app')

@section('title', 'Form Jenis Imunisasi')



@section('content')
<div class="row ">  
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Jenis Imunisasi</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($jenis_imunisasi->id)) ? route('jenis_imunisasi.store') : route('jenis_imunisasi.update', $jenis_imunisasi->id) }}" method="post">
                    @csrf
                    @isset($jenis_imunisasi->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">       
                        <label>Nama Imunisasi</label>
                        <input type="text" placeholder="Nama Jenis Imunisasi" class="form-control" name="nama_imunisasi" value="{{ old('nama_imunisasi', $jenis_imunisasi->nama_imunisasi) }}">
                    </div>
                    <div class="form-group">       
                        <label>Keterangan</label>
                        <textarea name="keterangan" class="form-control" placeholder="Masukan Keterangan (opsional)">{{ old('keterangan', $jenis_imunisasi->keterangan) }}</textarea>
                    </div>    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>    
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/jenis_imunisasi/index.blade.php
@extends('layouts.app')

@section('title', 'Jenis Imunisasi')



@section('content')
<div class="row ">  
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Jenis Imunisasi</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('jenis_imunisasi.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Jenis Imunisasi</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Jenis Imunisasi</th>
                            <th class="text-center">Keterangan</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($jenis_imunisasi as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama_imunisasi }}</td>
                            <td class="text-center">{{ $row->keterangan }}</td>
                            <td>
                                <form action="{{ route('jenis_imunisasi.destroy', $row->id) }}" method="post">
                                    <ul class="d-flex action-button">                                        
                                        <li><a href="{{ route('jenis_imunisasi.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                        @csrf
                                        @method('delete')
                                        {{-- <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li> --}}
                                    </ul>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection