routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', 'ParentLoginController@showLoginForm')->name('parent.showLoginForm');


Route::post('/ortu_login', 'ParentLoginController@login')->name('parent.login');
Route::post('/parent/logout', 'ParentLoginController@logout')->name('parent.logout');

Route::middleware('auth.parent:parent')->group(function(){
    Route::get('/parent/dashboard', 'DashboardController@index');
    Route::get('balita-anda', 'BalitaController@parentBabies');
    Route::get('pertumbuhan-balita-anda', 'PertumbuhanController@index')->name('pertumbuhan-balita-anda');
    Route::get('imunisasi-balita-anda', 'ImunisasiController@index')->name('imunisasi-balita-anda');
    Route::get('vitamin-balita-anda', 'VitaminController@index')->name('vitamin-balita-anda');
    Route::get('ubah-password', 'UbahPasswordController@index')->name('ubah-password');
    Route::post('ubah-password', 'UbahPasswordController@update')->name('ubah-password.update');
});
 
Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    
    Route::resource('jenis_imunisasi', 'JenisImunisasiController');    
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('balita', 'BalitaController');
    Route::resource('user', 'UserController');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');    

    Route::resource('pertumbuhan', 'PertumbuhanController');
    Route::resource('imunisasi', 'ImunisasiController');
    Route::resource('vitamin', 'VitaminController');

    Route::get('laporan', 'LaporanController@index')->name('laporan.index');

    Route::get('print-kunjungan/{jenis}/{tahun}', 'LaporanController@print')->name('print-kunjungan');
});

app/Balita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DateTime;

class Balita extends Model
{
    protected $table = 'balita';

    protected $fillable = [
        'nama_lengkap',
        'jenis_kelamin',
        'tempat_lahir',
        'tanggal_lahir',
        'orangtua_id',
    ];

    public function orangtua()
    {
        return $this->belongsTo('App\Orangtua');
    }

    public function getDefaultValues()
    {
        return [
            'nama_lengkap' => '',
            'jenis_kelamin' => '',
            'tempat_lahir' => '',
            'tanggal_lahir' => '',
            'orangtua_id' => '',
        ];
    }


    public function getUsia()
    {
        $tgl_lahir = new DateTime($this->tanggal_lahir);
        $now = new DateTime(date('Y-m-d'));
        $diff = $now->diff($tgl_lahir);
        $umur = $diff->y. ' Tahun '. $diff->m. ' Bulan';
        return $umur;
        // $umur = date('Y') - $tgl_lahir[0];
        // return $umur;
    }
}

app/Http/Controllers/BalitaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Balita;
use App\Orangtua;
use App\Http\Requests\StoreBalita;
use Auth;

class BalitaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $balita;

    public function __construct()
    {
        $this->balita = new Balita();
    }
    
    public function index()
    {
        return view ('balita.index', ['balita' => $this->balita->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['balita'] = (object) $this->balita->getDefaultValues();
        $data['orangtua'] = Orangtua::all();

        return view('balita.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBalita $request)
    {     
        Balita::create($request->all());
        return redirect()->route('balita.index')->with('success', 'Berhasil menambah data balita');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['balita'] = (object) $this->balita->find($id);
        $data['orangtua'] = Orangtua::all();

        return view('balita.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreBalita $request, $id)
    {
        $this->balita->find($id)->update($request->all());
        return redirect()->route('balita.index')->with('success', 'Berhasil mengubah data balita');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->balita->find($id)->delete();
        return redirect()->route('balita.index')->with('success', 'Berhasil menghapus data balita');
    }


    public function parentBabies()
    {
        //dd(Auth::user()->id);
        return view('parent.balita')->with('balita', Balita::where('orangtua_id', Auth::user()->id)->get());
    }
}

resources/views/balita/form.blade.php
@extends('layouts.app')

@section('title', 'Form Balita')

@section('content')
<div class="row ">  
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Data Balita</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($balita->id)) ? route('balita.store') : route('balita.update', $balita->id) }}" method="post">
                    @csrf
                    @isset($balita->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">       
                        <label>Nama Balita</label>
                        <input type="text" placeholder="Masukan Nama Lengkap Balita" class="form-control" name="nama_lengkap" value="{{ old('nama_lengkap', $balita->nama_lengkap) }}">
                    </div>
                    <div class="form-group">       
                        <label>Jenis Kelamin</label>
                        <select name="jenis_kelamin" class="form-control mySelect">
                            <option value=""> - Pilih Jenis Kelamin - </option>
                            <option value="l" {{ (old('jenis_kelamin') == 'l' || $balita->jenis_kelamin == 'l') ? 'selected' : '' }}> Laki - Laki</option>
                            <option value="p" {{ (old('jenis_kelamin') == 'p' || $balita->jenis_kelamin == 'p') ? 'selected' : '' }}> Perempuan</option>
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md-6">                    
                            <div class="form-group">       
                                <label>Tempat Lahir</label>
                                <input type="text" placeholder="Masukan Tempat Lahir Balita" class="form-control" name="tempat_lahir" value="{{ old('tempat_lahir', $balita->tempat_lahir) }}">
                            </div>
                        </div>
                        <div class="col-md-6">                        
                            <div class="form-group">       
                                <label>Tanggal Lahir</label>
                                <input type="text" placeholder="Masukan Tanggal Lahir Balita" class="form-control datepicker" name="tanggal_lahir" value="{{ old('tanggal_lahir', $balita->tanggal_lahir) }}">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">       
                        <label>Orang Tua</label>
                        <select name="orangtua_id" class="form-control mySelect">
                            <option value=""> - Pilih Orang Tua - </option>
                            @foreach($orangtua as $select)
                                <option value="{{ $select->id }}" {{ (old('orangtua_id') == $select->id || $balita->orangtua_id == $select->id) ? 'selected' : '' }}> {{ $select->nama_orangtua }}</option>
                            @endforeach                            
                        </select>
                    </div>
                                      
                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>    
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/balita/index.blade.php
@extends('layouts.app')

@section('title', 'Balita')



@section('content')
<div class="row ">  
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Balita</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('balita.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Balita</a>
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Balita</th>
                            <th>J. Kel</th>
                            <th>Tempat, Tgl. Lahir</th>
                            <th>Usia</th>
                            <th>Orangtua</th>                         
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($balita as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama_lengkap }}</td>
                            <td>{{ ($row->jenis_kelamin == 'l') ? 'Laki - Laki' : 'Perempuan' }}</td>
                            <td>{{ $row->tempat_lahir . ', ' . $row->tanggal_lahir }}</td>
                            <td>{{ $row->getUsia() }}</td>
                            <td>{{ $row->orangtua->nama_orangtua }}</td>             
                           
                            <td>
                                <form action="{{ route('balita.destroy', $row->id) }}" method="post">
                                    <ul class="d-flex action-button">                                        
                                        <li><a href="{{ route('balita.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                        @csrf
                                        @method('delete')
                                        {{-- <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li> --}}
                                    </ul>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection