routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', 'ParentLoginController@showLoginForm')->name('parent.showLoginForm');


Route::post('/ortu_login', 'ParentLoginController@login')->name('parent.login');
Route::post('/parent/logout', 'ParentLoginController@logout')->name('parent.logout');

Route::middleware('auth.parent:parent')->group(function(){
    Route::get('/parent/dashboard', 'DashboardController@index');
    Route::get('balita-anda', 'BalitaController@parentBabies');
    Route::get('pertumbuhan-balita-anda', 'PertumbuhanController@index')->name('pertumbuhan-balita-anda');
    Route::get('imunisasi-balita-anda', 'ImunisasiController@index')->name('imunisasi-balita-anda');
    Route::get('vitamin-balita-anda', 'VitaminController@index')->name('vitamin-balita-anda');
    Route::get('ubah-password', 'UbahPasswordController@index')->name('ubah-password');
    Route::post('ubah-password', 'UbahPasswordController@update')->name('ubah-password.update');
});
 
Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    
    Route::resource('jenis_imunisasi', 'JenisImunisasiController');    
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('balita', 'BalitaController');
    Route::resource('user', 'UserController');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');    

    Route::resource('pertumbuhan', 'PertumbuhanController');
    Route::resource('imunisasi', 'ImunisasiController');
    Route::resource('vitamin', 'VitaminController');

    Route::get('laporan', 'LaporanController@index')->name('laporan.index');

    Route::get('print-kunjungan/{jenis}/{tahun}', 'LaporanController@print')->name('print-kunjungan');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama', 'email', 'password', 'username'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getDefaultValues()
    {
        return [
            'nama' => '',
            'email' => '',
            'username' => '',
            'password' => ''
        ];
    }
    

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUser;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user;

    public function __construct()
    {
        $this->user = new User();
    }
    
    public function index()
    {
        return view ('user.index', ['users' => $this->user->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = (object) $this->user->getDefaultValues();

        return view('user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
    	$request['password'] = bcrypt($request['password']);
    	dd($request['password']);
        User::create($request->toArray());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data petugas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['user'] = (object) $this->user->find($id);

        return view('user.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, $id)
    {
        $this->user->find($id)->update($request->all());
        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data petugas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->find($id)->delete();
        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data petugas');
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form User')

@section('content')
<div class="row ">  
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Data user</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($user->id)) ? route('user.store') : route('user.update', $user->id) }}" method="post">
                    @csrf
                    @isset($user->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">       
                        <label>Nama User</label>
                        <input type="text" placeholder="Masukan Nama User" class="form-control" name="nama" value="{{ old('nama', $user->nama) }}">
                    </div>                    
                    <div class="form-group">       
                        <label>Email</label>
                        <input type="text" placeholder="Masukan Email" class="form-control" name="email" value="{{ old('email', $user->email) }}">
                    </div>
                    <div class="form-group">       
                        <label>Username</label>
                        <input type="text" placeholder="Masukan Username" class="form-control" name="username" value="{{ old('username', $user->username) }}">
                    </div>
                    @if(!isset($user->id))
                        <div class="form-group">       
                            <label>password</label>
                            <input type="password" placeholder="Masukan password" class="form-control" name="password" value="{{ old('password', $user->password) }}">
                        </div>
                    @endif
                    
                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>    
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'Petugas')

@section('content')
<div class="row ">  
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Petugas</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Petugas</a>
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Username</th>                         
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->username }}</td>
                           
                            <td>
                                <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                    <ul class="d-flex action-button">                                        
                                        <li><a href="{{ route('user.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                        @csrf
                                        @method('delete')
                                        {{-- <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li> --}}
                                    </ul>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection