routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/', 'ParentLoginController@showLoginForm')->name('parent.showLoginForm');


Route::post('/ortu_login', 'ParentLoginController@login')->name('parent.login');
Route::post('/parent/logout', 'ParentLoginController@logout')->name('parent.logout');

Route::middleware('auth.parent:parent')->group(function(){
    Route::get('/parent/dashboard', 'DashboardController@index');
    Route::get('balita-anda', 'BalitaController@parentBabies');
    Route::get('pertumbuhan-balita-anda', 'PertumbuhanController@index')->name('pertumbuhan-balita-anda');
    Route::get('imunisasi-balita-anda', 'ImunisasiController@index')->name('imunisasi-balita-anda');
    Route::get('vitamin-balita-anda', 'VitaminController@index')->name('vitamin-balita-anda');
    Route::get('ubah-password', 'UbahPasswordController@index')->name('ubah-password');
    Route::post('ubah-password', 'UbahPasswordController@update')->name('ubah-password.update');
});
 
Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    
    Route::resource('jenis_imunisasi', 'JenisImunisasiController');    
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('balita', 'BalitaController');
    Route::resource('user', 'UserController');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');    

    Route::resource('pertumbuhan', 'PertumbuhanController');
    Route::resource('imunisasi', 'ImunisasiController');
    Route::resource('vitamin', 'VitaminController');

    Route::get('laporan', 'LaporanController@index')->name('laporan.index');

    Route::get('print-kunjungan/{jenis}/{tahun}', 'LaporanController@print')->name('print-kunjungan');
});

app/Orangtua.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Orangtua extends Authenticatable
{
    use Notifiable;
    
    protected $table = 'orangtua';

    protected $fillable = [
        'nama_orangtua',
        'alamat',
        'no_telp',
        'email',
        'username',
        'password',        
    ];

    protected $hidden = ['password'];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }

    public function balita()
    {
        return $this->hasMany('App\Balita');
    }

    public function getDefaultValues()
    {
        return [
            'nama_orangtua' => '',
            'alamat' => '',
            'no_telp' => '',
            'email' => '',
            'username' => '',
            'password' => ''
        ];
    }
}

app/Http/Controllers/OrangtuaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Orangtua;
use App\Http\Requests\StoreOrangtua;

class OrangtuaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $orangtua;

    public function __construct()
    {
        $this->orangtua = new Orangtua();
    }
    
    public function index()
    {
        return view ('orangtua.index', ['orangtua' => $this->orangtua->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['orangtua'] = (object) $this->orangtua->getDefaultValues();

        return view('orangtua.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrangtua $request)
    {
        Orangtua::create($request->all());
        return redirect()->route('orangtua.index')->with('success', 'Berhasil menambah data orang tua');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['orangtua'] = (object) $this->orangtua->find($id);

        return view('orangtua.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreOrangtua $request, $id)
    {
        $this->orangtua->find($id)->update($request->all());
        return redirect()->route('orangtua.index')->with('success', 'Berhasil mengubah data orang tua');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->orangtua->find($id)->delete();
        return redirect()->route('orangtua.index')->with('success', 'Berhasil menghapus data Orang tua');
    }
}

resources/views/orangtua/form.blade.php
@extends('layouts.app')

@section('title', 'Form Orang Tua')

@section('content')
<div class="row ">  
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Data Orangtua</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($orangtua->id)) ? route('orangtua.store') : route('orangtua.update', $orangtua->id) }}" method="post">
                    @csrf
                    @isset($orangtua->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">       
                        <label>Nama Orang Tua</label>
                        <input type="text" placeholder="Masukan Nama Orang Tua" class="form-control" name="nama_orangtua" value="{{ old('nama_orangtua', $orangtua->nama_orangtua) }}">
                    </div>
                    <div class="form-group">       
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan alamat">{{ old('alamat', $orangtua->alamat) }}</textarea>
                    </div>
                    <div class="form-group">       
                        <label>No. Telp</label>
                        <input type="text" placeholder="Masukan No Telp" class="form-control" name="no_telp" value="{{ old('no_telp', $orangtua->no_telp) }}">
                    </div>
                    <div class="form-group">       
                        <label>Email</label>
                        <input type="text" placeholder="Masukan Email" class="form-control" name="email" value="{{ old('email', $orangtua->email) }}">
                    </div>
                    <div class="form-group">       
                        <label>Username</label>
                        <input type="text" placeholder="Masukan Username" class="form-control" name="username" value="{{ old('username', $orangtua->username) }}">
                    </div>
                    @if(!isset($orangtua->id))
                        <div class="form-group">       
                            <label>password</label>
                            <input type="password" placeholder="Masukan password" class="form-control" name="password" value="{{ old('password', $orangtua->password) }}">
                        </div>
                    @endif
                    
                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>    
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/orangtua/index.blade.php
@extends('layouts.app')

@section('title', 'Orang Tua')

@section('content')
<div class="row ">  
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Orang Tua Balita</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('orangtua.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Orang Tua</a>
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Ortu</th>
                            <th>Alamat</th>
                            <th>No. Telp</th>
                            <th>Email</th>
                            <th>Username</th>                         
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orangtua as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama_orangtua }}</td>
                            <td>{{ $row->alamat }}</td>
                            <td>{{ $row->no_telp }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->username }}</td>
                           
                            <td>
                                <form action="{{ route('orangtua.destroy', $row->id) }}" method="post">
                                    <ul class="d-flex action-button">                                        
                                        <li><a href="{{ route('orangtua.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                        @csrf
                                        @method('delete')
                                        {{-- <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li> --}}
                                    </ul>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection